---
output: github_document
---

# darkR

<!-- badges: start -->
<!-- badges: end -->

darkR only consists of an rstheme file that can be used to change the theme in Rstudios to resemble
the github dark default theme. Disclaimer: I have little to no experience in CSS, this was just a fun
project to change my R color theme because I like the github dark color scheme. There might be some
repetitions in the code since my edits were a little messy. My rstheme file is an edited version of 
Ben Harrap's linked here: https://github.com/benharrap/rsthemes.git

He also has a great tutorial on how to modify your own rsthemes file in case you want to create
your own theme. 

## Installation

You can install the development version of darkR like so:

``` bash
cd /your/personal/directory
git clone https://github.com/AmandaKwok28/darkR.git

```
Another (probably easier option) : 
You can also download the file directly and save it in your personal directory

## Usage

To use the rstheme, open Rstudio and hit tools --> Global Options --> Appearance then in the 
drop down list of editor themes, the Add... button and navigate to the rsthemes file you just
downloaded. Finally, hit apply. 


## How to Modify

To modify this rstheme file, open the rstheme file in Rstudio. Rstudio has 4 boxes that open up.
In the top left box (the editor), navigate to it's bottom right corner and there should be a menu
that allows you to change the language of your file. Make sure to set that to CSS so that R knows 
how to read it. This allows gives you a preview of all the hexadecimal colors in the file so you
don't need to apply the theme everytime to check your colors.

To actually apply the theme, navigate to editor themes (as detailed in Usage section) and remove your 
theme then re-add it. Hit apply and the changes should show. 
